from metasearchmcp.contracts import (
    GoogleSearchEnvelope,
    GoogleSearchRequest,
    ProviderPayload,
    ProviderReport,
    ProviderResult,
    ProviderStatus,
    SearchEnvelope,
    SearchHit,
    SearchOptions,
    SearchParams,
    SearchReport,
    SearchRequest,
    SearchResponse,
    SearchResult,
)
